language: cpp
sudo: required
dist: trusty

os:
    -linux

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get -gg update
    - sudo apt-get install libssl-dev
    - sudo apt-get install libgtkmm-3.0-dev
    - sudo apt-get install cmake
    - cmake .

script: make


