language: cpp
sudo: required
dist: trusty

os:
    -linux

compiler:
    - gcc
#    - clang

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install --yes libssl-dev
    - sudo apt-get install --yes libgtkmm-3.0-dev
    - sudo apt-get install --yes cmake
    - cmake .

script: make


